Cambios README y script prune

diff --git a/borgcron-prune-server b/borgcron-prune-server
--- a/borgcron-prune-server
+++ b/borgcron-prune-server
@@ -18,6 +18,7 @@ CLIENTS="/etc/lunix/borg/client"
 PRUNE_PREFIX="null"
 exitcode=0
 exitcode_create=0
+LOG_FILE="/var/log/borg/borg-prune.log"
 
 # Overwrite config variables
 # to include client name
@@ -47,7 +48,7 @@ evaluateExitCodes() {
 	case $1 in
 		2 )
 			error_log "Borg exited with fatal error." #(2)
-			echo "$CONFIG: 0" > /etc/lunix/borg_prune_status
+			echo "$CONFIG: ERROR" >> /etc/lunix/borg_prune_status
 
 			# ignore last try
 			if [ "$i" -lt "$RETRY_NUM" ]; then
@@ -69,15 +70,15 @@ evaluateExitCodes() {
 			;;
 		1 )
 			error_log "Borg had some WARNINGS, but everything else was okay."
-			echo "1" > /etc/lunix/borg_prune_status
+			echo "$CONFIG: OK" >> /etc/lunix/borg_prune_status
 			;;
 		0 )
 			info_log "Borg has been successful."
-			echo "1" > /etc/lunix/borg_prune_status
+			echo "$CONFIG: OK" >> /etc/lunix/borg_prune_status
 			;;
 		* )
 			error_log "Unknown error with code $1 happened."
-			echo "0" > /etc/lunix/borg_prune_status
+			echo "$CONFIG: ERROR" >> /etc/lunix/borg_prune_status
 			;;
 	esac
 }
@@ -253,7 +254,7 @@ getInfoAboutLastBackup() {
 # add trap to catch backup interruptions
 trapterm() {
 	rm_lock 2> /dev/null
-	echo "0" > /etc/lunix/borg_prune_status
+	echo "$CONFIG: ERROR" > /etc/lunix/borg_prune_status
 	error_log "Backup $BACKUP_NAME (PID: $$) interrupted by $1."
 	exit 2
 }
@@ -278,29 +279,30 @@ do
 	source $CONFIG
 	overwrite_vars;
 
+	# check that variables are set
+	if [ "$BACKUP_NAME" = "" ] ||
+	[ "$BORG_REPO" = "" ] ||
+	[ "$BACKUP_DIRS" = "" ]; then
+		error_log "Some required variables may not be set in the config file. Skipping prune for \"$CONFIG\" ."
+		exit 2
+	fi
+	if ! export|grep -q "BORG_REPO"; then
+		error_log "The BORG_REPO variable is not exported in the config file. Skipping prune for \"$CONFIG\" ."
+		exit 2
+	fi
+
 	# check lock
 	if is_lock; then
 		error_log "Backup $BACKUP_NAME is locked. Prevent start."
 		exit 1
 	fi
 
-	# check that variables are set
-	if [ "$BACKUP_NAME" = "" ] ||
-	[ "$BORG_REPO" = "" ] ||
-	[ "$BACKUP_DIRS" = "" ]; then
-		error_log 'Some required variables may not be set in the config file. Cancel backup.'
-		exit 2
-	fi
-	if ! export|grep -q "BORG_REPO"; then
-		error_log 'The BORG_REPO variable is not exported in the config file. Cancel backup.'
-		exit 2
-	fi
 
 	# The (optional) prefix makes sure only backups from this machine with this
 	# backup-type are touched.
 	# ($PRUNE_PARAMS intentionally not quoted)
 
-	if [ "$PRUNE_PARAMS" ] && [ "$exitcode" -lt 2 ]; then
+	if [ "$PRUNE_PARAMS" ] ; then
 		info_log "Running prune for \"$BACKUP_NAME\"…"
 
 		# if RETRY_NUM_PRUNE is not set, fall back to RETRY_NUM
